### ISSUE TITLE
Performance benchmark against Jitsi?

### ISSUE THREAD

**Issue by StarMonk** [pion/ion-app-web#43]
Is there any chart of performance benchmark against Jitsi?

**Comment by leewardbound** [comment]
Hey @StarMonk, we currently don't have any comparative benchmarks like this, with Jitsi or any other platform, but we'd love your help to make them! One of the maintainers has run a small-scale test, the results are here https://github.com/pion/ion/blob/master/docs/production/stress_test.md and there's the great `pion/ion-load-test` project for testing exactly like this. Most of the core developers are more immediately focused on core features than load testing at this stage, but the question still comes up a lot!

Anecdotally speaking, being written in `golang` instead of Java, in my experience the resource usage of `ion` has been much lower. I used to run some small Jitsi servers and IMHO it was heavy even with no users live :joy: and joining several clients seemed to have a noticeable effect (but I've never seen `ion` cpu budge at all). We're seeking volunteers to help out -- we need to decide what factors to test, establish a testing ritual, run the benchmarks on various hardware at various scales, and fill in this docs page with much more in-depth results; I agree it'd be pretty cool if we also had a "compared to Jitsi" column, that is useful information!
